user-default-points: 0
point-name: point
point-name-plural: points
command-blocks:
  give: false  
database-type: yaml
database-host:
database-name:
database-username:
database-password:
database-table-rewards:
database-table-users:
