name: BOSRewards
main: ievans3024.bosrewards.main.BOSRewards
version: 0.0.8.9
author: ievans3024
website: http://www.bhslaughter.com/
commands:
  rewards:
    aliases: bosrewards
    description: "Main command for BOSRewards"
    permission: BOSRewards.user.*
    permission-message: You do not have permission to use rewards.
    usage:
    - "/rewards [command] [args]"
    - "Aliases: /rw"
    - "Try /rewards help or /rewards help [command] for more info."
  rw:
    aliases: bosrw
    description: "Shorthand version of main command for BOSRewards"
    permission: BOSRewards.user.*
    permission-message: You do not have permissions to use rewards.
    usage:
    - "/rw [command] [args]"
    - "Alias for /rewards"
    - "Try /rw help or /rw help [command] for more info."
permissions:
  BOSRewards.*:
    description: All BOSRewards permissions
    default: op
    children:
      BOSRewards.admin.*: true
      BOSRewards.user.*: true
      BOSRewards.util.*: true
  BOSRewards.admin.*:
    description: All BOSRewards admin permissions
    default: false
    children:
      BOSRewards.admin.givepoints: true
      BOSRewards.admin.takepoints: true
      BOSRewards.admin.setpoints: true
      BOSRewards.admin.seebalance: true
      BOSRewards.admin.seehistory: true
      BOSRewards.admin.bypass: true
      BOSRewards.admin.info: true
  BOSRewards.user.*:
    description: All normal user permissions
    default: true
    children:
      BOSRewards.user.list: true
      BOSRewards.user.balance: true
      BOSRewards.user.redeem: true
      BOSRewards.user.help: true
      BOSRewards.user.history: true
  BOSRewards.util.*:
    description: All utility permissions
    default: false
    children:
      BOSRewards.util.reload: true
      BOSRewards.util.dumpsql: true
      BOSRewards.util.createreward: true
      BOSRewards.util.removereward: true
      BOSRewards.util.editreward: true
      