name: BOSRewards
main: arpinity.bosrewards.BOSRewards
version: 0.0.2.3
author: arpinity3024
website: http://www.bhslaughter.com/
commands:
  test\ command:
    usage: |
  rewards:
    aliases: bosrewards
    description: "Main command for BOSRewards"
    permission: |
    permission-message: You do not have permission to use rewards.
    usage: |
      "/rewards [command] [args]"
      "Aliases: /bosrewards, /rw"
      "Try /rewards help or /rewards help [command] for more info."
  rw:
    aliases: bosrw
    description: "Shorthand version of main command for BOSRewards"
    permission: |
    permission-message: You do not have permissions to use rewards.
    usage: |
      "/rw [command] [args]"
      "Alias for /rewards"
      "Try /rw help or /rw help [command] for more info."
    